colors:
  body: none
  date: YELLOW
  tags: BLUE
  title: none
default_hour: 23
default_minute: 59
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: /mnt/d/Documents/journal.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v4.2.1
