[line_break]
disabled = true

[character]
success_symbol = "ğŸ’š"
error_symbol = "ğŸ’”"
vicmd_symbol = "â® "

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
disabled = false
time_format = "%H%M hrs"

[git_status]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = false
