[line_break]
disabled = true

[character]
success_symbol = "ğŸ’š"
error_symbol = "ğŸ’”"
use_symbol_for_status = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[time]
disabled = false
time_format = "%H%M hrs"
